### ISSUE TITLE
[Incomplete] Implement suite of music playing commands

### ISSUE THREAD

**Issue by Crisu07** [ThatOneKidChris/ChummyBot#5]
**Discord does not support playing music from Youtube anymore and switching to Spotify is much more complicated and slower with the server the bot is hosted on so we decided to pass on music features.**

**To-Do IN ORDER**
* [x] Main Functions like Play, Resume, Pause
* [x] Search Function instead of pasting Youtube Link
* [ ] Queue Feature to handle multiple songs at once
* [ ] Play Next/Skip, Shuffle, Remove/Edit Queues Feature for song queues
